### ISSUE TITLE
ItemLink is a little janky

### ISSUE THREAD

**Issue by BadMagic100** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#176]
**Describe the bug**
When sending an item to an itemlink where you are a participant, you will see 2 UI popups - one for the item you sent to the item link, and one for the item you received from the itemlink (which are the same item).
**To Reproduce**
In 2 saves, add an item link like:
```yaml
item_links:
     - name: everygrubby
       item_pool:
          - Grub
       replacement_item: null
```

Go find and collect everygrubby's grub

**Expected behavior**
 You should only see one popup.

**Screenshots**
![image](https://github.com/ArchipelagoMW-HollowKnight/Archipelago.HollowKnight/assets/10623820/0f22505d-4586-4227-96a9-c5160b4e012b)
