### ISSUE TITLE
RandomCharmCosts incorrectly exported to YAML file

### ISSUE THREAD

**Issue by SKCrawford** [ArchipelagoMW-HollowKnight/Archipelago.HollowKnight#232]
**Describe the bug**
When exporting options to YAML, the variable `RandomCharmCosts` does not properly export. When I select `'-2'`, the exported file has the variable set to `'0'`.

**To Reproduce**
1. Go to the Hollow Knight options page.
2. Change the setting corresponding to the variable `RandomCharmCosts` to `'-2'`.
3. Export the options.
4. Open the YAML file and observe the value of `RandomCharmCosts`. For me, it is `'0'`.

**Expected behavior**
It should not be `'0'`.

**Workaround**
1. Open the Hollow Knight settings YAML file.
2. Manually change the value from `'0'` to the desired value.

**Additional context**
Below are the other settings I used. Note that `RandomCharmCosts` is `'0'` despite setting it to `'-2'`.

```
name: REMOVED
game: Hollow Knight
description: Generated by https://archipelago.gg/ for Hollow Knight
Hollow Knight:
  progression_balancing: '50'
  accessibility: items
  RandomizeDreamers: 'true'
  RandomizeSkills: 'true'
  RandomizeFocus: 'false'
  RandomizeSwim: 'true'
  RandomizeCharms: 'true'
  RandomizeKeys: 'true'
  RandomizeMaskShards: 'true'
  RandomizeVesselFragments: 'true'
  RandomizeCharmNotches: 'true'
  RandomizePaleOre: 'true'
  RandomizeGeoChests: 'false'
  RandomizeJunkPitChests: 'false'
  RandomizeRancidEggs: 'true'
  RandomizeRelics: 'true'
  RandomizeWhisperingRoots: 'true'
  RandomizeBossEssence: 'false'
  RandomizeGrubs: 'true'
  RandomizeMimics: 'true'
  RandomizeMaps: 'true'
  RandomizeStags: 'true'
  RandomizeLifebloodCocoons: 'false'
  RandomizeGrimmkinFlames: 'false'
  RandomizeJournalEntries: 'false'
  RandomizeNail: 'false'
  RandomizeGeoRocks: 'false'
  RandomizeBossGeo: 'false'
  RandomizeSoulTotems: 'false'
  RandomizeLoreTablets: 'false'
  RandomizeElevatorPass: 'true'
  PreciseMovement: 'false'
  ProficientCombat: 'false'
  BackgroundObjectPogos: 'false'
  EnemyPogos: 'false'
  ObscureSkips: 'false'
  ShadeSkips: 'false'
  InfectionSkips: 'false'
  FireballSkips: 'false'
  SpikeTunnels: 'false'
  AcidSkips: 'false'
  DamageBoosts: 'false'
  DangerousSkips: 'false'
  DarkRooms: 'false'
  ComplexSkips: 'false'
  DifficultSkips: 'false'
  RemoveSpellUpgrades: 'false'
  StartLocation: king's_pass
  Goal: any
  WhitePalace: exclude
  ExtraPlatforms: 'true'
  AddUnshuffledLocations: 'false'
  StartingGeo: '600'
  DeathLink: 'false'
  DeathLinkShade: shade
  DeathLinkBreaksFragileCharms: 'false'
  MinimumGeoPrice: '1'
  MaximumGeoPrice: '400'
  MinimumGrubPrice: '1'
  MaximumGrubPrice: '23'
  MinimumEssencePrice: '1'
  MaximumEssencePrice: '1400'
  MinimumCharmPrice: '1'
  MaximumCharmPrice: '20'
  RandomCharmCosts: '0'
  MinimumEggPrice: '1'
  MaximumEggPrice: '10'
  EggShopSlots: '5'
  SlyShopSlots: '8'
  SlyKeyShopSlots: '6'
  IseldaShopSlots: '5'
  SalubraShopSlots: '5'
  SalubraCharmShopSlots: '5'
  LegEaterShopSlots: '3'
  GrubfatherRewardSlots: '7'
  SeerRewardSlots: '8'
  ExtraShopSlots: '0'
  SplitCrystalHeart: 'false'
  SplitMothwingCloak: 'false'
  SplitMantisClaw: 'false'
  CostSanity: 'off'
  CostSanityHybridChance: '10'
  CostSanityEggWeight: '1'
  CostSanityGrubWeight: '1'
  CostSanityEssenceWeight: '1'
  CostSanityCharmWeight: '1'
  CostSanityGeoWeight: '8'
  start_inventory:
    Gathering_Swarm: 1
```
